### ISSUE TITLE
AttributeError: module 'google_auth_httplib2' has no attribute 'AuthorizedHttp'

### ISSUE THREAD

**Issue by halhwadi** [googleapis/google-auth-library-python-httplib2#53]
I'm working on [firebase cloud messaging service SDK python](https://firebase.google.com/docs/cloud-messaging/send-message) and I'm able to send msg to single device (token) but when i tried to send MultiCastMessage I got the below error , I have clone this repositry to get the latest google-auth-httplib2, however I ended up with below error which has no relevant results in google, I can see AuthorizedHttp class in google-auth-httplib2.py, please advise?

**Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\firebase_admin\messaging.py", line 167, in send_multicast
    return _get_messaging_service(app).send_all(messages, dry_run)
  File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\firebase_admin\messaging.py", line 377, in send_all
    transport = self._build_transport(self._credential)
  File "C:\Users\Husam.Alhwadi\Envs\test\lib\site-packages\googleapiclient\_auth.py", line 117, in authorized_http
    return google_auth_httplib2.AuthorizedHttp(credentials, http=build_http())
AttributeError: module 'google_auth_httplib2' has no attribute 'AuthorizedHttp'**

 
#### Environment details

  - OS type and version: windows 10
  - Python version: `python --version`3.9
  - pip version: `pip --version` 21.2.4
  - `google-auth-httplib2` version: `pip show google-auth-httplib2`

#### Steps to reproduce

  1. 
  2. ?

#### Code example

```

import google_auth_httplib2
>>> import Bikum.settings as settings
>>> import firebase_admin
>>> from firebase_admin import messaging
>>> from firebase_admin import credentials
>>> from django.contrib.auth.models import User
>>> from chat.models import TokenModel
>>> user_sys = User.objects.get(email='driver6@bikum.org')
>>> tokens = TokenModel.objects.get(user_sys=user_sys).value
>>> cred = credentials.Certificate(settings.GOOGLE_APPLICATION_CREDENTIALS)
>>> default_app = firebase_admin.initialize_app(cred)
>>> message = messaging.MulticastMessage(data={'score': '850','time': '2:45'}, notification=messaging.Notification(title= '21Nov', body= 'thanks god'),toke
ns=tokens)
>>> response = messaging.send_multicast(message)

```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by halhwadi** [comment]
its solved..

solution steps:
1-clone the  google_auth_http2" because pip didn't install the complete stuff, only dist file is there..
2- change the import statement in _auth.py line 28) in googleapiclient package :

from:
`import google_auth_httplib2`

To:
```
try:
    import google_auth_httplib2_0.google_auth_httplib2 as google_auth_httplib2

```
take care to rename the google_auth_httplib2_XXXX folder to any other name rather than "google_auth_httplib2", In my case ; I changed to google_auth_httplib2_0
